# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a3bab4c56d1cd0746d1ea9365fcfa7ac5d39856e05dd03677de20dda5233f8513bd344b43c99a7c55e50d0844c2b1415194819c3595165523b540006b58474c

test:
  secret_key_base: 8162b603863aad6ffd48a8d5d53b59e97b077c34b19546727676e91761dbd13fdef48c8846dbc625fcce3100c03d010db1773ad7a2ce2f07d820cfaab8a792a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
